apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopsapp
  template:
    metadata:
      labels:
        app: devopsapp
    spec:
      containers:
      - name: devopsapp
        image: 181957455825.dkr.ecr.ap-south-1.amazonaws.com/devops_cicd:latest
        ports:
        - containerPort: 8081
